### PR TITLE
Skipping instant deep linking on forcing new session

### PR DESCRIPTION
**Pull request by sojanpr**
Skipping instant deep linking on forcing new session.
Force new session carries the Branch link in the intent. In this case SDK need to talk to the Branch server to retrieve the referring params

@EvangelosG @ahmednawar @aaustin

### CODE REVIEW

**Comment by aaustin** [comment]
👍

**Comment by EvangelosG** [comment]
👍

**Comment by ayaziqbal** [comment]
I want referral make app

**Comment by EvangelosG** [comment]
Hi @ayaziqbal -- please contact our wonderful support team integrations@branch.io with a bit more context and they'll help you out!

**Pull request merged**
