### PR TITLE
[INTENG-4676][INTENG-4809]: Add support for push edge case

### PR DESCRIPTION
**Pull request by aaustin**
@code-crusher FYI

### CODE REVIEW

**Comment by code-crusher** [comment]
Nice!!! Though I'm also seeing an edge case with this because now the callback gets triggered on every resume without a Branch link, such as opening a notification but without a Branch link or switching from a different activity with no intent data. Then the` branch.getLatestReferringParams()` have `{}` which gets back in the `deferredInitListener_`. We should add a check for empty JSON here https://github.com/BranchMetrics/android-branch-deep-linking/blob/36c5adc61c100433c4399611ab2ce4a3b0b923ee/Branch-SDK/src/io/branch/referral/ServerRequestRegisterOpen.java#L93 to ensure we do not fire unnecessary callbacks. Do you have any other thoughts to prevent this?

**Comment by code-crusher** [comment]
Hey, @apeterson-branch I have cleaned up the Branch for you to merge and deploy the SDK.

**Comment by code-crusher** [comment]
👍

**Comment by apeterson-branch** [comment]
This solution didn't work in my sample app.

**Comment by csalmi-branch** [comment]
Due to some of the changes in this PR, code compilation now fails. I'm reverting this change for further investigation.

**Pull request merged**
