### PR TITLE
Avoid race condition

### PR DESCRIPTION
**Pull request by mateherber**
Fetch WeakReference value to local variable to avoid race condition which ends up in npe.

### CODE REVIEW

**Comment by EvangelosG** [comment]
Hi @mateherber -- how is this different from the line you removed?

`Context context = (currentActivityReference_ != null && currentActivityReference_.get() != null) ? currentActivityReference_.get().getApplicationContext() : null;`

Let me know!

**Comment by mateherber** [comment]
Hi @EvangelosG!

In the second case after **currentActivityReference_.get() != null** and before **currentActivityReference_.get().getApplicationContext()** weakreference can be dismissed so second get can be null even if the nullcheck passed just before. If you cache it in a local variable (hold the strong reference) it is not the case

**Comment by sojanpr** [comment]
@mateherber  Thanks for mentioning it. Since this method is executed on Main thread do you think there is chance for Weak reference of Activity can change before and after of the  `if` statement?

**Comment by mateherber** [comment]
@sojanpr We're getting nullptr exceptions using this version right there in production.

**Comment by sojanpr** [comment]
@mateherber  Thanks for the  update. Even though couldn't find the way for this to happen, agree with you that above is the best practice when dealing with weak references. We will add this with our next release

**Pull request merged**
