### PR TITLE
Update UniversalResourceAnalyser.java to fix UntaggedSocketViolation

### PR DESCRIPTION
**Pull request by radixdev**
Fix for `UntaggedSocketViolation` on Android O

```
2019-04-04 16:41:43.953 com.appboy.sample D/StrictMode: StrictMode policy violation: android.os.strictmode.UntaggedSocketViolation: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage
        at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2023)
        at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:82)
        at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:50)
        at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:313)
        at libcore.io.IoBridge.socket(IoBridge.java:640)
        at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:124)
        at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:128)
        at java.net.Socket.createImpl(Socket.java:489)
        at java.net.Socket.getImpl(Socket.java:552)
        at java.net.Socket.setSoTimeout(Socket.java:1180)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:139)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
        at io.branch.referral.UniversalResourceAnalyser$UrlSkipListUpdateTask.doInBackground(UniversalResourceAnalyser.java:166)
        at io.branch.referral.UniversalResourceAnalyser$UrlSkipListUpdateTask.doInBackground(UniversalResourceAnalyser.java:148)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

### CODE REVIEW

**Comment by radixdev** [comment]
@sojanpr @aaustin

**Comment by aaustin** [comment]
@apeterson-branch Can you review & approve?

**Comment by apeterson-branch** [comment]
Merging directly to master is not allowed.  Please point merge requests to Staging.

**Comment by radixdev** [comment]
@apeterson-branch done

**Comment by apeterson-branch** [comment]
I'm trying to reproduce the issue, and haven't been successful yet.   Before applying the change I did the following:
1. Spun up an Android "O" emulator
2. Added StrictMode to the Branch-SDK-TestBed app
3. Added a log statement (instead of the proposed fix) to show that line of code is exercised
4. Searched the logs for "Untagged"

I can see my log statement, but don't see any StrictMode violations in this area.  I do see other StrictMode violations in other areas of the code, but not Untagged.  These were previously documented with Jira tickets SDK-262 and SDK-264.

Note that the proposed fix needs an import statement to compile.

**Comment by radixdev** [comment]
@apeterson-branch Ah my mistake, I made the PR in the online editor 😅. I'll create a test app for reproduction purposes.

**Comment by radixdev** [comment]
Reproduced on https://github.com/radixdev/branch-untagged-socket-repro
Note that I originally saw this on an Android P device, but I also could repro on an Android O emulator.

My emulator info:

```


Name: API_26_Nexus_5X_Android_O

CPU/ABI: Google Play Intel Atom (x86)

Path: /Users/juliancontreras/.android/avd/API_26_Nexus_5X_Android_O.avd

Target: google_apis_playstore [Google Play] (API level 26)

Skin: 1080x1920

SD Card: 100 MiB

hw.dPad: no

hw.lcd.height: 1920

runtime.network.speed: full

hw.accelerometer: yes

hw.device.name: Nexus 5X

vm.heapSize: 256

skin.dynamic: yes

hw.device.manufacturer: Google

hw.lcd.width: 1080

hw.gps: yes

hw.initialOrientation: Portrait

skin.path.backup: _no_skin

image.androidVersion.api: 26

hw.audioInput: yes

image.sysdir.1: system-images/android-26/google_apis_playstore/x86/

tag.id: google_apis_playstore

showDeviceFrame: no

hw.camera.back: emulated

hw.mainKeys: no

AvdId: API_26_Nexus_5X_Android_O

hw.camera.front: emulated

hw.lcd.density: 420

avd.ini.displayname: API 26 Nexus 5X Android O

hw.gpu.mode: auto

hw.device.hash2: MD5:ae200ad6786ec467cb9067f7b46b0fd1

hw.ramSize: 1536

hw.trackBall: no

PlayStore.enabled: true

fastboot.forceColdBoot: no

hw.battery: yes

hw.cpu.ncore: 4

hw.sdCard: yes

tag.display: Google Play

runtime.network.latency: none

hw.keyboard: yes

hw.sensors.proximity: yes

disk.dataPartition.size: 800M

hw.sensors.orientation: yes

avd.ini.encoding: UTF-8

hw.gpu.enabled: yes
```

**Pull request merged**
